#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

filetype="$( file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file" < /dev/null > /dev/tty
    exit 1
fi

MIME=$(mimetype --all --brief "$1")
case "$MIME" in
    *application/pdf*)
        pdftotext "$1" -
        ;;
    *text/plain*)
        batcat --force-colorization --paging=never --style=changes,numbers --terminal-width $(($2 - 3)) "$1" && false
        ;;
esac
pistol "$file"
